[package]
name = "viewer"
version = "0.1.0"
edition = "2024"

[features]
default = ["bevy/dynamic_linking"]
release = []

[dependencies]
anyhow = "1.0.98"
bevy = "0.16.0"
prost = "0.13.5"
tokio = { version = "1.45.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"

